version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spekan
    command: ['/bin/sh', '-c', 'rm -f tmp/pids/server.pid && bin/dev']
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
      - "35729:35729"
      - "3036:3036"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      EDITOR: vim
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:3306' #Seaquel Pro接続用にポートずらしておく
    volumes:
      - ./tmp/db:/var/lib/mysql
    cap_add:
      - SYS_NICE

volumes:
  gem_data:

